apps/client/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("add/", views.register_client, name="register_client"),
    path("list/", views.client_list, name="client_list"),
    path("update/<int:pk>", views.update_client, name="update_client"),
    path("delete/<int:pk>", views.delete_client, name="delete_client"),
    path("import/", views.import_client_data, name="import_client_data"),
    path("delete-confirm/", views.delete_confirm, name="delete_confirm"),
    path(
        "seven-hills-registration/",
        views.seven_hills_registration_view,
        name="seven_hills_registration",
    ),
    path("seven-hills", views.seven_hills_list, name="seven_hills_list"),
    path(
        "seven-hills/update/<int:pk>",
        views.update_seven_hills,
        name="update_seven_hills",
    ),
    path(
        "seven-hills/delete/<int:pk>",
        views.delete_seven_hills,
        name="delete_seven_hills",
    ),
    path(
        "seven-hills/details/<int:pk>",
        views.seven_hills_details,
        name="seven_hills_details",
    ),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path

from apps.users.forms import LoginForm
from apps.users.views import (
    ChangePasswordView,
    CustomLoginView,
    ResetPasswordView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.users.urls")),
    path(
        "login/",
        CustomLoginView.as_view(
            redirect_authenticated_user=True,
            template_name="accounts/login.html",
            authentication_form=LoginForm,
        ),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="accounts/logout.html"),
        name="logout",
    ),
    path("password-reset/", ResetPasswordView.as_view(), name="password_reset"),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("password-change/", ChangePasswordView.as_view(), name="password_change"),
    re_path(r"^oauth/", include("social_django.urls", namespace="social")),
    path("child/", include("apps.child.urls")),
    path("sponsor/", include("apps.sponsor.urls")),
    path("sponsorship/", include("apps.sponsorship.urls")),
    path("staff/", include("apps.staff.urls")),
    path("finance/", include("apps.finance.urls")),
    path("client/", include("apps.client.urls")),
    path("reports/", include("apps.reports.urls")),
    path("dashboard/", include("apps.dashboard.urls")),
    path("loans/", include("apps.loans.urls")),
    # Inventory ulrs
    path("customers/", include("apps.inventory.customers.urls")),
    path("products/", include("apps.inventory.products.urls")),
    path("sales/", include("apps.inventory.sales.urls")),
    path("supplier/", include("apps.inventory.supplier.urls")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
        path("__debug__/", include("debug_toolbar.urls")),
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/client/models.py
import datetime
from datetime import date
from django.core.validators import (
    FileExtensionValidator,
    RegexValidator,
    MinValueValidator,
    MaxValueValidator,
    EmailValidator,
)
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from cloudinary.models import CloudinaryField


# Clients registration
class Client(models.Model):
    # Basic info
    reg_number = models.CharField(
        max_length=10,
        verbose_name="Registration ID",
        null=True,
        blank=True,
        default="G01-001",
    )
    full_name = models.CharField(
        max_length=50,
        verbose_name="Full Name",
        validators=[
            RegexValidator(
                r"^[A-Za-z]+(?:\s[A-Za-z]+)*$", "Only letters and spaces are allowed"
            )
        ],
    )
    picture = CloudinaryField(
        "client_uploads",
        validators=[FileExtensionValidator(allowed_extensions=["jpg", "jpeg", "png"])],
        null=True,
        blank=True,
    )
    mobile_telephone = PhoneNumberField(
        verbose_name="Mobile Telephone", null=True, blank=True, default="+256999999999"
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created at")
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "client_info"
        verbose_name = "Client Bio Data"
        verbose_name_plural = "Clients Bio Data"

    def __str__(self):
        return self.full_name


# 7Hills registration
class SevenHillsRegistration(models.Model):
    registration_date = models.DateField()
    full_name = models.CharField(max_length=255)
    GENDER_CHOICES = [
        ("M", "Male"),
        ("F", "Female"),
    ]
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    date_of_birth = models.DateField(
        null=True,
        blank=True,
        verbose_name="Date of Birth",
        validators=[
            MinValueValidator(limit_value=datetime.date(year=1900, month=1, day=1)),
            MaxValueValidator(limit_value=datetime.date.today()),
        ],
    )

    AGE_BRACKET_CHOICES = [
        ("0-17", "0 – 17"),
        ("18-25", "18 – 25"),
        ("26-34", "26 – 34"),
        ("35-45", "35 – 45"),
        ("46+", "46 and above"),
    ]
    age_bracket = models.CharField(max_length=10, choices=AGE_BRACKET_CHOICES)

    MARITAL_STATUS_CHOICES = [
        ("Single", "Single"),
        ("Married", "Married"),
        ("Widowed", "Widowed"),
        ("Divorced", "Divorced"),
        ("Domestic Partnership", "In a Domestic Partnership"),
    ]
    marital_status = models.CharField(max_length=50, choices=MARITAL_STATUS_CHOICES)
    spouse_name = models.CharField(max_length=255, blank=True, null=True)
    spouse_contact = PhoneNumberField(blank=True, null=True)

    number_of_children = models.PositiveIntegerField(blank=True, null=True)
    boys = models.PositiveIntegerField(blank=True, null=True)
    girls = models.PositiveIntegerField(blank=True, null=True)

    CHILDREN_AGE_BRACKETS = [
        ("0-5", "0-5 years"),
        ("6-10", "6-10 years"),
        ("11-15", "11-15 years"),
        ("16-18", "16-18 years"),
    ]
    children_age_brackets = models.CharField(max_length=20, blank=True, null=True)

    highest_education = models.CharField(max_length=255)
    home_village = models.CharField(max_length=255)
    residence = models.CharField(max_length=255)
    email = models.EmailField(validators=[EmailValidator()])
    telephone_1 = PhoneNumberField()
    telephone_2 = PhoneNumberField(blank=True, null=True)

    next_of_kin = models.CharField(max_length=255)
    next_of_kin_telephone_1 = PhoneNumberField()
    next_of_kin_telephone_2 = PhoneNumberField(blank=True, null=True)
    relationship_with_next_of_kin = models.CharField(max_length=255)

    workplace = models.CharField(max_length=255, blank=True, null=True)

    SAVINGS_FREQUENCY_CHOICES = [
        ("Daily", "Daily"),
        ("Weekly", "Weekly"),
        ("Monthly", "Monthly"),
    ]
    savings_frequency = models.CharField(
        max_length=10, choices=SAVINGS_FREQUENCY_CHOICES, blank=True, null=True
    )
    min_savings_amount = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True
    )
    saving_goal = models.TextField(blank=True, null=True)

    SERVICES_INTERESTED = [
        ("Savings Scheme", "Join Savings Scheme"),
        ("Skills Training", "Skills Training"),
        ("Share Group", "Join Share Group"),
        ("Community Unit", "Join Community Unit"),
        ("Discipleship", "Discipleship"),
        ("Volunteering", "Volunteering"),
    ]
    services_interested = models.CharField(
        max_length=50, choices=SERVICES_INTERESTED, blank=True, null=True
    )

    MINISTRY_GROUPS = [
        ("Ushering", "Ushering"),
        ("Evangelism", "Evangelism"),
        ("Children Ministry", "Children's Ministry"),
        ("Youth Ministry", "Youth Ministry"),
        ("Intercession", "Intercession"),
        ("Choir", "Choir"),
        ("Hospitality", "Hospitality"),
        ("Media", "Media"),
    ]
    ministry_groups = models.CharField(
        max_length=50, choices=MINISTRY_GROUPS, blank=True, null=True
    )

    dc_makerere_association_year = models.PositiveIntegerField(
        blank=True, null=True, validators=[MinValueValidator(1900)]
    )
    recommended_by = models.CharField(max_length=255, blank=True, null=True)
    preferred_contact_method = models.CharField(max_length=255, blank=True, null=True)
    additional_comments = models.TextField(blank=True, null=True)
    agrees_to_photo_use = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.full_name}"

    @property
    def prefixed_id(self):
        if self.pk < 10:
            return f"7H00{self.pk}"
        elif self.pk < 100:
            return f"7H0{self.pk}"
        else:
            return f"7H{self.pk}"

    def calculate_age(self):
        today = date.today()
        age = (
            today.year
            - self.date_of_birth.year
            - (
                (today.month, today.day)
                < (self.date_of_birth.month, self.date_of_birth.day)
            )
        )
        return age

apps/client/forms.py
from django import forms

from .models import Client, SevenHillsRegistration


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = "__all__"

    def clean_full_name(self):
        full_name = self.cleaned_data.get("full_name")
        if len(full_name) < 3:
            raise forms.ValidationError("Full name must be at least 3 characters long.")
        return full_name

    def clean(self):
        cleaned_data = super().clean()
        full_name = cleaned_data.get("full_name")

        if len(full_name) < 3:
            self.add_error("full_name", "Full name must be at least 3 characters long.")
            self.fields["full_name"].widget.attrs.update(
                {"class": "form-control is-invalid"}
            )

        return cleaned_data


# Import form
class ImportClientsForm(forms.Form):
    excel_file = forms.FileField()
    excel_file.widget.attrs["class"] = "form-control-file"


class SevenHillsRegistrationForm(forms.ModelForm):
    class Meta:
        model = SevenHillsRegistration
        fields = "__all__"
        widgets = {
            "registration_date": forms.DateInput(
                attrs={"type": "date", "class": "form-control"}
            ),
            "date_of_birth": forms.DateInput(
                attrs={"type": "date", "class": "form-control"}
            ),
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            "telephone_1": forms.TextInput(attrs={"class": "form-control"}),
            "telephone_2": forms.TextInput(attrs={"class": "form-control"}),
            "next_of_kin_telephone_1": forms.TextInput(attrs={"class": "form-control"}),
            "next_of_kin_telephone_2": forms.TextInput(attrs={"class": "form-control"}),
            "min_savings_amount": forms.NumberInput(attrs={"class": "form-control"}),
            "saving_goal": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
            "additional_comments": forms.Textarea(
                attrs={"class": "form-control", "rows": 3}
            ),
        }

    def clean_full_name(self):
        full_name = self.cleaned_data.get("full_name")
        if len(full_name) < 3:
            raise forms.ValidationError("Full name must be at least 3 characters long.")
        return full_name

    def clean(self):
        cleaned_data = super().clean()
        spouse_name = cleaned_data.get("spouse_name")
        marital_status = cleaned_data.get("marital_status")

        if marital_status == "Married" and not spouse_name:
            self.add_error(
                "spouse_name", "Spouse name is required for married individuals."
            )

        return cleaned_data

templates/sdms/client/bulk_import.html
{% extends 'loans/base.html' %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock %}

{% block content %}

<div class="container">
    <div class="page-header flex-wrap">
        <h3 class="mb-0"> {{form_name|upper}}<span class="pl-0 h6 pl-sm-2 text-muted d-inline-block"></h3>
        <div class="d-flex">
            <a title="Register Child" class="btn btn-sm ml-3 btn-success" href="{% url 'register_client' %}"><i
                    class="mdi mdi-account-plus btn-icon-prepend"></i></a>
            <a title="View List..." class="btn btn-sm ml-3 btn-success" href="{% url 'client_list' %}"><i
                    class="mdi mdi-chart-line btn-icon-prepend"></i>
            </a>
            <a title="Bulk Import" class="btn btn-sm ml-3 btn-success" href="{% url 'import_client_data' %}"><i
                    class="mdi mdi-upload btn-icon-prepend"></i></a>

        </div>
    </div>
    <hr>

    <div class="form-content my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-5">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <!--  -->
                            <input type="file" name="excel_file" accept=".xls,.xlsx">
                            <div class="form-group mt-4 mb-0">
                                <button type="submit" class="col-md-12 btn btn-dark"
                                    onclick="return confirm('Are you sure you want import?') && validateForm()">
                                    IMPORT DATA</button> </div>
                        </form>
                    </div>
                    <!-- table -->
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

templates/sdms/client/client_list.html
{% extends 'loans/base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <div class="page-header flex-wrap">
        <h3 class="mb-0">{{table_title|upper}}<span class="pl-0 h6 pl-sm-2 text-muted d-inline-block"></span></h3>
        <div class="d-flex">
            <button title="Print" type="button" class="btn btn-sm ml-3 btn-success" onclick=" printDiv('printMe')">
                <i class="mdi mdi-printer btn-icon-prepend"></i> </button>

            <button title="Export To Excel" type="button" class="btn btn-sm ml-3 btn-success"
                onclick="ExportToExcel('xlsx')">
                <i class="mdi mdi-file-excel btn-icon-prepend"></i> </button>

            <button title="Export To Word" type="button" class="btn btn-sm ml-3 btn-success"
                onclick="Export2Doc('printMe');">
                <i class="mdi mdi-file-word btn-icon-prepend"></i> </button>

            <a title="Register Client" class="btn btn-sm ml-3 btn-success" href="{% url 'register_client' %}"><i
                    class="mdi mdi-account-plus btn-icon-prepend"></i>
            </a>

            <a title="View List..." class="btn btn-sm ml-3 btn-success" href="{% url 'client_list' %}"><i
                    class="mdi mdi-chart-line btn-icon-prepend"></i>
            </a>
            <a title="Bulk Import" class="btn btn-sm ml-3 btn-success" href="{% url 'import_client_data' %}"><i
                    class="mdi mdi-upload btn-icon-prepend"></i></a>

            <form action="{% url 'delete_confirm' %}" method="post">
                {% csrf_token %}
                <button title="Delete All" class="btn btn-sm ml-3 btn-danger btn-sm" type="submit"
                    onclick="return confirm('Are you sure about this? all records will be deleted permanently');"><i
                        class="mdi mdi-cancel btn-icon-prepend"></i></button>
            </form>
        </div>
    </div>
    <form method="GET" action="{% url 'client_list' %}">
        <input type="text" name="search" id="searchInput" onkeyup="searchTable()" placeholder="Search..."
            style="border-radius: 5px; height: 35px;">
        <button type="submit" class="btn btn-sm ml-3 btn-success"><i class="mdi mdi-magnify"></i></button>
        </a>
    </form>

    <div id="printMe" class="tab-pane show active">
        <header style="text-align: center;">
        </header>
        <hr class="bg-info" style="height: 3px;" />
        <div class="table-responsive">

            <table class="my-table" id="dataTable">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Reg.No</th>
                        <th scope="col">Picture</th>
                        <th scope="col">Client Name</th>
                        <th scope="col">Telephone</th>
                        <th scope="col" colspan="2">Action</th>

                    </tr>
                </thead>
                <tbody class="table-group-divider">
                    {%for client in records%}
                    <tr>
                        <th scope="row">{{forloop.counter}}.</th>
                        <td>{{client.reg_number}}</td>
                        <td>
                            {% if client.picture %}
                            <a title="Click to update picture" href="{% url 'update_picture' %}"
                                onclick="return confirm('Are you sure you want to update client picture? ');">
                                <img class="rounded-circle account-img" height="50" width="50"
                                    src="{{ client.picture.url }}" alt="">
                            </a>
                            {% else %}
                            No Picture!
                            {% endif %}
                        </td>
                        <td>{{client.full_name}}</td>
                        <td>{{client.mobile_telephone}}</td>
                        <td>
                            {% if user.profile.role == 'administrator' or user.profile.role == 'manager' or user.profile.role == 'staff' %}
                            <a class="btn btn-primary btn-sm" title="Edit" href="{% url 'update_client' client.id %}"><i
                                    class="bi bi-pencil"></i></a>
                            {% else %}
                            <button class="btn btn-primary btn-sm" onclick="showNoPermissionMessage('edit')">
                                <i class="bi bi-pencil"></i>
                            </button>
                            {% endif %}
                        </td>
                        <td>
                            {% if user.profile.role == 'administrator' or user.profile.role == 'manager' %}
                            <a class="btn btn-danger btn-sm" title="Erase" href="{% url 'delete_client' client.id %}"
                                onclick="return confirm('Are you sure about this? This record will be deleted permanently.');">
                                <i class="bi bi-trash"></i>
                            </a>
                            {% else %}
                            <button class="btn btn-danger btn-sm disabled" onclick="showNoPermissionMessage('delete')">
                                <i class="bi bi-trash"></i>
                            </button>
                            {% endif %}
                        </td>
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
            <hr class="bg-info" style="height: 3px;" />

            <!-- Pagination links &raquo;  -->
            <div class="pagination">
                <span class="step-links">
                    {% if records.has_previous %}
                    <a href="?page=1">
                        <!-- first -->
                        <svg xmlns="http://www.w3.org/2000/svg" width="1.2em" height="1.2em" viewBox="0 0 16 16">
                            <path fill="#2375e1"
                                d="M14 3.002a1 1 0 0 0-1.578-.816l-7 4.963a1 1 0 0 0-.007 1.628l7 5.037A1 1 0 0 0 14 13.003zM2 2.5a.5.5 0 0 1 1 0v11a.5.5 0 0 1-1 0z" />
                        </svg> </a>
                    <a href="?page={{ records.previous_page_number }}">
                        <!-- previous -->
                        <svg xmlns="http://www.w3.org/2000/svg" width="1.2em" height="1.2em" viewBox="0 0 20 20">
                            <path fill="#2375e1" d="m4 10l9 9l1.4-1.5L7 10l7.4-7.5L13 1z" /></svg>
                    </a>
                    {% endif %}

                    <span class="current">
                        Page {{ records.number }} of {{ records.paginator.num_pages }}.
                    </span>

                    {% if records.has_next %}
                    <a href="?page={{ records.next_page_number }}">
                        <!-- Next -->
                        <svg xmlns="http://www.w3.org/2000/svg" width="1.2em" height="1.2em" viewBox="0 0 20 20">
                            <path fill="#2375e1" d="M7 1L5.6 2.5L13 10l-7.4 7.5L7 19l9-9z" /></svg>
                    </a>
                    <a href="?page={{ records.paginator.num_pages }}">
                        <!-- last  -->
                        <svg xmlns="http://www.w3.org/2000/svg" width="1.2em" height="1.2em" viewBox="0 0 28 28">
                            <path fill="#2375e1"
                                d="M23.5 3.75a.75.75 0 0 1 1.5 0v20.5a.75.75 0 0 1-1.5 0zM3 5.254C3 3.438 5.041 2.37 6.533 3.406l12.504 8.68a2.25 2.25 0 0 1 .013 3.688l-12.504 8.81C5.056 25.634 3 24.57 3 22.745z" />
                        </svg>
                        </svg>
                    </a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

templates/sdms/client/client_register.html
{% extends 'loans/base.html' %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock %}

{% block content %}

<div class="container">
    <div class="page-header flex-wrap">
        <h3 class="mb-0"> {{form_name|upper}}<span class="pl-0 h6 pl-sm-2 text-muted d-inline-block"></span></h3>
        <div class="d-flex">
            <a title="Register Child" class="btn btn-sm ml-3 btn-success" href="{% url 'register_client' %}"><i
                    class="mdi mdi-account-plus btn-icon-prepend"></i></a>
            <a title="View List..." class="btn btn-sm ml-3 btn-success" href="{% url 'client_list' %}"><i
                    class="mdi mdi-chart-line btn-icon-prepend"></i>
            </a>
            <a title="Bulk Import" class="btn btn-sm ml-3 btn-success" href="{% url 'import_client_data' %}"><i
                    class="mdi mdi-upload btn-icon-prepend"></i></a>
        </div>
    </div>
    <hr>

    <div class="form-content my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-5">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <!--  -->
                            {{ form|crispy }}
                            <div class="form-group mt-4 mb-0">
                                <button type="submit" class="col-md-12 btn btn-dark"
                                    onclick="return confirm('Are you sure you want to proceed?') && validateForm()">
                                    REGISTER CLIENT</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

templates/sdms/client/seven_hills_profile_rpt.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head %}

{% endblock %}

{% block content %}
  <div class="container">
    <div class="page-header flex-wrap">
      <h3 class="mb-0">{{ table_title|upper }}<span class="pl-0 h6 pl-sm-2 text-muted d-inline-block"></span></h3>

      <div class="d-flex">
        <button title="Print PDF" type="button" class="btn btn-sm ml-3 btn-success" onclick=" printDiv('printMe')"><i class="mdi mdi-printer btn-icon-prepend"></i></button>

        <button title="Export To Excel" type="button" class="btn btn-sm ml-3 btn-success" onclick="ExportToExcel('xlsx')"><i class="mdi mdi-file-excel btn-icon-prepend"></i></button>

        <button title="Export To Word" type="button" class="btn btn-sm ml-3 btn-success" onclick="Export2Doc('printMe');"><i class="mdi mdi-file-word btn-icon-prepend"></i></button>

        <a title="Register Child" class="btn btn-sm ml-3 btn-success" href="{% url 'seven_hills_registration' %}"><i class="mdi mdi-account-plus btn-icon-prepend"></i></a>
        <a title="View List..." class="btn btn-sm ml-3 btn-success" href="{% url 'seven_hills_list' %}"><i class="mdi mdi-chart-line btn-icon-prepend"></i></a>
      </div>
    </div>
    <hr />
    <div id="printMe" class="tab-pane show active">
      <header style="text-align: center;">
        <i style="font-size: 2em; font-family: 'Lucida Calligraphy', 'Lucida Sans Unicode', sans-serif;" class="text-success">{{ record.full_name }}</i> -
        <i style="font-size: 2em;">Profile</i>
      </header>
      <table class="my-table">
        <tr>
          <td class="text-white bg-info" colspan="4">
            <b>Basic Info</b>
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <i class="text-info">Registration Date:</i> {{ record.registration_date }}
          </td>
          <td colspan="2">
            <i class="text-info">Full Name:</i> {{ record.full_name }}
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <i class="text-info">Gender:</i> {{ record.get_gender_display }}
          </td>
          <td colspan="2">
            <i class="text-info">Date of Birth:</i> {{ record.date_of_birth }}
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <i class="text-info">Age Bracket:</i> {{ record.get_age_bracket_display }}
          </td>
          <td colspan="2">
            <i class="text-info">Marital Status:</i> {{ record.get_marital_status_display }}
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <i class="text-info">Spouse Name:</i> {{ record.spouse_name }}
          </td>
          <td colspan="2">
            <i class="text-info">Spouse Contact:</i> {{ record.spouse_contact }}
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <i class="text-info">Number of Children:</i> {{ record.number_of_children }}
          </td>
          <td colspan="2">
            <i class="text-info">Children Age Brackets:</i> {{ record.children_age_brackets }}
          </td>
        </tr>
        <tr>
          <td class="text-white bg-info" colspan="4">
            <b>Contact Details</b>
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <i class="text-info">Email:</i> {{ record.email }}
          </td>
          <td colspan="2">
            <i class="text-info">Telephone 1:</i> {{ record.telephone_1 }}
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <i class="text-info">Telephone 2:</i> {{ record.telephone_2 }}
          </td>
          <td colspan="2">
            <i class="text-info">Residence:</i> {{ record.residence }}
          </td>
        </tr>
        <tr>
          <td class="text-white bg-info" colspan="4">
            <b>Next of Kin</b>
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <i class="text-info">Name:</i> {{ record.next_of_kin }}
          </td>
          <td colspan="2">
            <i class="text-info">Telephone 1:</i> {{ record.next_of_kin_telephone_1 }}
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <i class="text-info">Telephone 2:</i> {{ record.next_of_kin_telephone_2 }}
          </td>
          <td colspan="2">
            <i class="text-info">Relationship:</i> {{ record.relationship_with_next_of_kin }}
          </td>
        </tr>
        <tr>
          <td class="text-white bg-info" colspan="4">
            <b>Additional Information</b>
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <i class="text-info">Savings Frequency:</i> {{ record.get_savings_frequency_display }}
          </td>
          <td colspan="2">
            <i class="text-info">Min Savings Amount:</i> {{ record.min_savings_amount }}
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <i class="text-info">Services Interested:</i> {{ record.get_services_interested_display }}
          </td>
          <td colspan="2">
            <i class="text-info">Ministry Groups:</i> {{ record.get_ministry_groups_display }}
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <i class="text-info">Recommended By:</i> {{ record.recommended_by }}
          </td>
          <td colspan="2">
            <i class="text-info">Preferred Contact Method:</i> {{ record.preferred_contact_method }}
          </td>
        </tr>
        <tr>
          <td colspan="4">
            <i class="text-info">Additional Comments:</i> {{ record.additional_comments }}
          </td>
        </tr>
      </table>
    </div>
  </div>
{% endblock %}